-- ACTUALIZACIÓN PARA GUARDADO DE PROGRESO INDIVIDUAL POR FOTO
ALTER TABLE evidencias_obra 
ADD COLUMN IF NOT EXISTS progreso_2 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS progreso_3 INTEGER DEFAULT 0;

-- Notificar recarga de caché
NOTIFY pgrst, 'reload schema';
